package com.revature.BankSystem.Profile;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

//LOMBOK ANNOTATIONS
@Data // includes ToString, EqualsAndHashCode, Getter, and Setter Annotations
@NoArgsConstructor // builds a no-args constructor to reduce boiler plate code
@AllArgsConstructor // builds an all args constructor to reduce boiler plate code

// JAKARTA ANNOTATIONS
@Entity // shows that the class represents a data object that should be persisted, requires an id for a primary key and a no-arg constructor
@Table(name = "profile") // defines what table a class should belong to
public class Profile {
    @Id // makes a public key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // allows the primary key to be generated by the database itself
    private int id;

    @Column(unique = true, nullable = false)
    private String username;

    @Column(nullable = false)
    private String password;

    @Column(unique = true, nullable = false)
    @Email(message = "Your email")
    private String email;

    @Column(nullable = false)
    private String firstname;

    @Column(nullable = false)
    private String lastname;

    @Column(nullable = false)
    private String address;

    @Column(nullable = false)
    private String userType;

    public Profile(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public Profile(String username, String password, String email, String firstname, String lastname, String address, String userType) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.address = address;
        this.userType = userType;
    }
}